### ISSUE TITLE
Issues for Custom Fields -> Sections

### ISSUE THREAD

**Issue by sanderpotjer** [QuatreCentQuatre/craft-dummy-data#3]
Looks like a promising & useful plugin!

Testing it and encountering some issues. Haven't configured anything yet beside Users tab. 

<img width="1459" alt="Scherm­afbeelding 2024-10-10 om 15 22 32" src="https://github.com/user-attachments/assets/63e335a1-6260-4f4f-be11-becfd6d1f0b8">

When trying to execute the script:

```
Exception 'TypeError' with message 'Cannot access offset of type string on string'

in /vendor/quatrecentquatre/craft-dummy-data/src/services/DummyCustomFieldService.php:113

Stack trace:
#0 /vendor/quatrecentquatre/craft-dummy-data/src/services/DummyCustomFieldService.php(44): quatrecentquatre\dummydata\services\DummyCustomFieldService->updateTitleField()
#1 /vendor/quatrecentquatre/craft-dummy-data/src/console/controllers/GenerateController.php(102): quatrecentquatre\dummydata\services\DummyCustomFieldService->clean()
#2 [internal function]: quatrecentquatre\dummydata\console\controllers\GenerateController->actionIndex()
#3 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#6 /vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#7 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('dummy-data/gene...', Array)
#8 /vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('dummy-data/gene...', Array)
#9 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('dummy-data/gene...', Array)
#10 /vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#12 /craft(27): yii\base\Application->run()
#13 {main}
```

An empty array is set, so the count check on line 107 doesn't work.

When I do set a section config the script fails as well: 

```
Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'database.sections' doesn't exist
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.sections' doesn't exist'

in /vendor/yiisoft/yii2/db/Command.php:1320
```

Looks like the table prefix (which is set) is missing in the SQL statement.

**Comment by rgauthier4c4** [comment]
@sanderpotjer Which version of CraftCms are you using? 

And it seem i've forgot about the table prefix, I'll add the support for it and I'll let you know when it's released.

**Comment by sanderpotjer** [comment]
@rgauthier4c4 thanks! This was tested on a Craft 4.12.4 installation.

**Comment by rgauthier4c4** [comment]
@sanderpotjer The bug is fixed and the table prefixes were added to the plugin in v4.0.13.

**Comment by sanderpotjer** [comment]
@rgauthier4c4 bug fix confirmed, now working as expected. Thanks for the quick update!
